version: "3.3"

services:
    db:
      image: mysql:8
      volumes:
        - mariadbvol:/var/lib/mysql
      restart: always
      env_file:
        - .env
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      networks:
          - monresau
      command:
            - '--default-authentication-plugin=mysql_native_password'
    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      volumes:
        - wordpressvol:/var/www/html
      restart: always
      environment:
       - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
       - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
       - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
       - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      networks:
          - monresau
    nginx:
        depends_on:
            - wordpress
        image: nginx:alpine
        ports:
          - "8080:80"    # http
          - "8443:443"
        links:
            - wordpress
        volumes:
            - /media/sf_rendu/Inception/srcs/requirements/nginx/conf/:/etc/nginx/conf.d/default.conf
            - wordpressvol:/var/www/html
            - ${NGINX_SSL_CERTS}:/etc/ssl:ro
            - ${NGINX_LOGS}:/var/log/nginx
        networks:
            - monresau
networks:
    monresau:
        driver: bridge
volumes:
    mariadbvol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/jperras/data/db
    wordpressvol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/jperras/data/wordpress
